import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";

const isProduction = process.argv[2] === 'production';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: isProduction ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
};

if (isProduction) {
	esbuild.build(buildOptions).then(() => {
		process.exit(0);
	}).catch((error) => {
		console.error(error);
		process.exit(1);
	});
} else {
	esbuild.context(buildOptions).then((ctx) => {
		ctx.watch();
	}).catch((error) => {
		console.error(error);
		process.exit(1);
	});
}

